/*
 * This source file was generated by the Gradle 'init' task
 */
package org.orgst;

public class App {
    String[] yes_ins = {"Yes","yes","Y","y"};
   
    public static void main(String[] args) {
        Methods.head();
        while (true){
        String Cmd = Methods.input();
        switch (Cmd) {
            case "run": org.orgst.Extras.ChannelViewer.CV(args);
            case "help":
                System.out.println("Cmd's: pride, clear, help, orgid, hist, git, sauce, esc, run, super"); 
                break;
            case "sauce":
                Methods.sauce();
                break;
            case "clear":
                Methods.clear();
                break;
            case "hist":
                Methods.hist();
                break;
            case "orgid":
                Methods.orgid();
                break;
            case "pride":
                Methods.flag();
                break;
            case "esc":
                System.exit(0);
                break;
            case "git":
                System.out.println(org.orgst.Variables.AppData.AppData.get("GitHub"));
            default:
                break;
        }
    }
    }
}
