/*
 * This source file was generated by the Gradle 'init' task
 */
package org.orgst;
public class App {
    String[] yes_ins = {"Yes","yes","Y","y"};

    public static void main(String[] args) {
        String Cmd = Methods.head();
        switch (Cmd) {
            case "help":
                System.out.println("CMDS: hist, git, sauce, esc, run, super"); 
                break;
            
            default:
                break;
        }
    }
}
